Repository wecode-bootcamp-korea/32-1st-88stationery-frontend, pull requests merged in 2022-05, with the labels that each got.

#12 [ 32기 이수광 ] Login 페이지 token 연결 수정
  src/config.js
  src/pages/Login/Login.js
Labels: Status: Accepted

#10 [32기 최규성] Modify: Nav바 카테고리 수정 및 로그인 버튼 모달화 + 검색 필터 기능 추가
  public/images/items/mainImage1.png
  public/images/items/mainImage2.png
  public/images/items/mainImage3.png
  src/Router.js
  src/components/Aside/Aside.js
  src/components/Aside/Aside.scss
  src/components/Carousel/Carousel.js
  src/components/Carousel/Carousel.scss
  src/components/Modal/Login.scss
  src/components/Modal/LoginFormLayout.js
  src/components/Modal/LoginModal.js
  src/components/Nav/Nav.js
  src/components/Nav/NavSideCategory.js
  src/components/Search/Search.js
  src/components/Search/Search.scss
Labels: Status: Accepted

#5 [32기 이현석] 회원가입 기능 구현 ( 리뷰 반영 완료)
  package-lock.json
  package.json
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
  src/styles/mixins.scss
Labels: Status: Accepted

#6 [32기 정덕우] 제품상세페이지 구현
  src/Router.js
  src/pages/Goods/Goods.js
  src/pages/Goods/Goods.scss
Labels: Status: Accepted

#13 [32기 최규성] Main 캐러셀 기능 구현 및 수정 사항 Fix
  public/images/main/main.md
  public/images/main/mainBanner.png
  src/Router.js
  src/components/Aside/Aside.js
  src/components/Aside/Aside.scss
  src/components/Aside/AsideGlobalChange.js
  src/components/ItemContainer/ItemContainer.js
  src/components/ItemContainer/ItemContainer.scss
  src/components/Items/Items.js
  src/components/Items/items.scss
  src/components/ItemsCarousel/Items.js
  src/components/ItemsCarousel/ItemsCarousel.js
  src/components/ItemsCarousel/ItemsCarousel.scss
  src/components/Modal/Login.scss
  src/components/Modal/LoginFormLayout.js
  src/components/Modal/LoginModal.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/NavSideCategory.js
  src/config.js
  src/pages/Category/Category.js
  src/pages/Category/Category.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
Labels: Status: 리뷰 요청

#8 [ 32기 이수광 ] Inquiry 문의 페이지 제작
  public/data/comments.json
  public/data/items.json
  src/pages/Inquiry/Inquiry.js
  src/pages/Inquiry/Inquiry.scss
  src/pages/Inquiry/Items/Comments/Comment.js
  src/pages/Inquiry/Items/Items.js
  src/pages/Inquiry/Items/ItemsComment.js
  src/pages/Inquiry/Items/ItemsList.js
Labels: Status: 리뷰 요청, Status: Conflict 해결 요청
